# Generated by Django 3.2.7 on 2021-09-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronmon',
            old_name='cronjob',
            new_name='status',
        ),
        migrations.AddField(
            model_name='cronmon',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
